/* School OS client app: usable guest mode + optional Supabase cloud sync. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:'Good morning.',assignments:'Assignments',calendar:'Calendar',notes:'Notes',study:'Study',tempo:'Tempo',classes:'Classes',grades:'Grades',exams:'Exams',languages:'Languages',settings:'Settings'};
const tables=['subjects','assignments','exams','notes','sessions','classes','grades','plans','vocab','decks','goals','habits','notifications'];
let sb=null,state={user:null,assignments:[],exams:[],notes:[],sessions:[],classes:[],subjects:[],grades:[],plans:[],vocab:[],decks:[],goals:[],habits:[],notifications:[]};
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const fmt=d=>d?new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'No date';
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function toast(msg){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.style='position:fixed;right:24px;bottom:24px;z-index:100;padding:13px 16px;border:1px solid rgba(214,179,106,.3);border-radius:12px;background:#15120d;color:#f1d18b;font:12px Inter,Arial;box-shadow:0 12px 40px #0008';document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2600)}
const guestKey='school-os-guest-v1';
function guestData(){try{return JSON.parse(localStorage.getItem(guestKey)||'{}')}catch{return {}}}
function saveGuest(){localStorage.setItem(guestKey,JSON.stringify(Object.fromEntries(tables.map(t=>[t,state[t]||[]]))))}
function guestLoad(){const d=guestData();for(const t of tables)state[t]=Array.isArray(d[t])?d[t]:[];renderAll()}
async function requireUser(){if(state.user)return state.user;toast('Using Guest Mode. Your data is saved on this device.');return {id:'guest',guest:true}}
function navRoute(){let id=location.hash.slice(1)||'dashboard';if(!titles[id])id='dashboard';$$('main section').forEach(s=>s.style.display=s.id===id?'block':'none');$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));$('#title').textContent=titles[id];if(id==='calendar')renderCalendar();if(id==='languages')renderLanguages();if(id==='grades')renderGrades();if(id==='classes')renderClasses();if(id==='tempo')renderTempo()}
window.addEventListener('hashchange',navRoute);$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
function addHeaderControls(){const h=$('header');const b=document.createElement('button');b.id='account';b.textContent='Guest Mode · Sign in';h.appendChild(b);b.onclick=async()=>{if(state.user){await sb.auth.signOut();state.user=null;b.textContent='Guest Mode · Sign in';guestLoad();toast('Signed out. Guest data is still on this device.');return}const email=prompt('Email');if(!email)return;const password=prompt('Password (6+ characters)');if(!password)return;let r=await sb.auth.signInWithPassword({email,password});if(r.error){const create=confirm('No account found. Create one?');if(create)r=await sb.auth.signUp({email,password})}if(r.error){toast(r.error.message);return}if(r.data.session){state.user=r.data.user;b.textContent='Sign out';await loadData();toast('Cloud sync enabled')}else{toast('Account created. Check your email if confirmation is enabled, then sign in.')}}}
async function init(){if(!window.SCHOOL_OS_SUPABASE_URL||!window.SCHOOL_OS_SUPABASE_KEY){guestLoad();return}sb=window.supabase.createClient(window.SCHOOL_OS_SUPABASE_URL,window.SCHOOL_OS_SUPABASE_KEY);addHeaderControls();const {data:{session}}=await sb.auth.getSession();state.user=session?.user||null;$('#account').textContent=state.user?'Sign out':'Guest Mode · Sign in';sb.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;$('#account').textContent=state.user?'Sign out':'Guest Mode · Sign in';if(state.user)loadData();else guestLoad()});if(state.user)await loadData();else guestLoad()}
async function load(table,query='*',order){let q=sb.from(table).select(query);if(order)q=q.order(order,{ascending:false});const {data,error}=await q.limit(200);if(error)throw error;return data||[]}
async function loadData(){try{const [subjects,assignments,exams,notes,sessions,classes,grades,plans,vocab,decks,goals,habits,notifications]=await Promise.all([load('subjects'),load('assignments','*','deadline'),load('exams','*','exam_at'),load('notes','*','updated_at'),load('study_sessions','*','started_at'),load('classes'),load('grades','*','graded_at'),load('tempo_plans','*','plan_date'),load('vocabulary','*','created_at'),load('flashcard_decks','*','created_at'),load('goals','*','target_date'),load('habits'),load('notifications','*','created_at')]);Object.assign(state,{subjects,assignments,exams,notes:notes.filter(n=>!n.deleted_at),sessions,classes,grades,plans,vocab,decks,goals,habits,notifications});renderAll()}catch(e){console.error(e);toast('Cloud load failed: '+e.message)}}
function renderEmpty(){guestLoad()}
function subjectName(id){return state.subjects.find(s=>s.id===id)?.name||''}
function renderAll(){renderAssignments();renderExams();renderNotes();renderStudy();renderClasses();renderGrades();renderLanguages();renderTempo();renderDashboard()}
function renderDashboard(){const a=state.assignments,done=a.filter(x=>x.status==='completed');$('#tasks').textContent=a.filter(x=>x.status!=='completed').length;$('#exams').textContent=state.exams.length;$('#notes').textContent=state.notes.length;const mins=state.sessions.reduce((s,x)=>s+(Number(x.actual_minutes)||0),0);$('#study').textContent=mins+'m';$('#progress').textContent=a.length?Math.round(done.length/a.length*100)+'%':'0%';$('#progressText').textContent=`${done.length} of ${a.length} assignments completed`;const open=a.filter(x=>x.status!=='completed').sort((x,y)=>(new Date(x.deadline||'2999')-new Date(y.deadline||'2999')));$('#next').textContent=open[0]?.title||'Nothing urgent';$('#nextMeta').textContent=open[0]?.deadline?'Due '+fmt(open[0].deadline):'You are caught up.';$('#upcoming').innerHTML=open.slice(0,5).map(x=>`<div class="item"><span>${esc(x.title)}</span><span class="muted">${x.deadline?fmt(x.deadline):''}</span></div>`).join('')||'<p class="muted">No upcoming assignments.</p>';$('#recent').innerHTML=state.notes.slice(0,5).map(x=>`<div class="item"><span>${esc(x.title)}</span></div>`).join('')||'<p class="muted">No notes yet.</p>'}
function renderAssignments(){const box=$('#assignmentList');box.innerHTML=state.assignments.length?state.assignments.map(x=>`<div class="item" data-id="${x.id}"><div><b>${esc(x.title)}</b><div class="muted">${subjectName(x.subject_id)} · ${x.deadline?fmt(x.deadline):'No deadline'} · ${x.status}</div></div><span>${x.priority?'P'+x.priority:''} <button data-act="done">${x.status==='completed'?'Undo':'Done'}</button> <button data-act="edit">Edit</button> <button data-act="delete">×</button></span></div>`).join(''):'<p class="muted">No assignments yet. Add your first one.</p>'}
function renderExams(){const box=$('#examList');box.innerHTML=state.exams.length?state.exams.map(x=>`<div class="item" data-id="${x.id}"><div><b>${esc(x.title)}</b><div class="muted">${subjectName(x.subject_id)} · ${fmt(x.exam_at)}</div></div><button data-act="delete">×</button></div>`).join(''):'<p class="muted">No exams yet.</p>'}
function renderNotes(){const grid=$('#notesGrid');grid.innerHTML=state.notes.length?state.notes.map(x=>`<div class="card" data-id="${x.id}"><small>NOTE ${x.pinned?'· PINNED':''}</small><h3>${esc(x.title||'Untitled')}</h3><p>${esc((x.body||'').slice(0,180))}</p><button data-act="edit">Edit</button> <button data-act="pin">${x.pinned?'Unpin':'Pin'}</button> <button data-act="delete">Delete</button></div>`).join(''):'<div class="card"><p class="muted">No notes yet.</p></div>'}
function renderStudy(){const total=state.sessions.reduce((s,x)=>s+(Number(x.actual_minutes)||0),0);$('#study').textContent=total+'m';const card=$('#study .columns .card:last-child');if(card)card.innerHTML='<h3>Study history</h3>'+state.sessions.slice(0,8).map(x=>`<div class="item"><span>${x.session_type||'focus'}</span><span>${x.actual_minutes||0} min</span></div>`).join('')||'<p class="muted">No completed sessions yet.</p>'}
function renderClasses(){const box=$('#classList');box.innerHTML=state.classes.length?state.classes.map(x=>`<div class="card"><small>${x.weekday==null?'CLASS':['SUN','MON','TUE','WED','THU','FRI','SAT'][x.weekday]}</small><h3>${esc(subjectName(x.subject_id)||'Class')}</h3><p>${esc(x.teacher||'')} ${x.room?'· '+esc(x.room):''}</p><p>${x.start_time||''} ${x.end_time?'– '+x.end_time:''}</p></div>`).join(''):'<div class="card"><p class="muted">No classes yet.</p></div>'}
function renderGrades(){const sec=$('#grades');if(!sec)return;const avg=state.grades.reduce((s,g)=>s+(g.score!=null&&g.max_score?Number(g.score)/Number(g.max_score)*100*Number(g.weight||1):0),0);const weights=state.grades.reduce((s,g)=>s+Number(g.weight||1),0);const card=sec.querySelector('.card');if(!card)return;card.innerHTML=`<div class="row"><div><small>WEIGHTED AVERAGE</small><h2>${weights?Math.round(avg/weights)+'%':'—'}</h2></div><button id="addGrade">+ Add grade</button></div><div class="list">${state.grades.map(g=>`<div class="item"><span>${esc(g.title)} · ${subjectName(g.subject_id)}</span><span>${g.score??'—'} / ${g.max_score??'—'} <button data-grade="${g.id}">×</button></span></div>`).join('')||'<p class="muted">Add your grades to track performance.</p>'}</div>`;$('#addGrade').onclick=addGrade}
function renderLanguages(){const sec=$('#languages');if(!sec)return;const cols=sec.querySelector('.columns');if(!cols)return;cols.innerHTML=`<div class="card"><div class="row"><h3>Vocabulary</h3><button id="addVocab">+ Add</button></div><p class="muted">${state.vocab.length} saved words</p>${state.vocab.slice(0,12).map(v=>`<div class="item"><span><b>${esc(v.word)}</b> · ${esc(v.meaning||'')}</span><button data-vocab="${v.id}">×</button></div>`).join('')}</div><div class="card"><h3>Practice</h3><p class="muted">Review your saved vocabulary.</p><button id="reviewVocab">Start review</button><div id="vocabReview"></div></div>`;$('#addVocab').onclick=addVocab;$('#reviewVocab').onclick=reviewVocab}
function renderTempo(){const plan=$('#planList');if(!plan)return;const items=[...state.assignments].filter(x=>x.status!=='completed').sort((a,b)=>scoreTask(b)-scoreTask(a));plan.innerHTML=items.slice(0,10).map((x,i)=>`<div class="item"><b>${i+1}. ${esc(x.title)}</b><span class="muted">${x.estimated_minutes||25} min · priority ${x.priority||3}</span></div>`).join('')||'<p class="muted">Add assignments first, then Tempo can build a plan.</p>'}
function scoreTask(x){const days=x.deadline?Math.max(.2,(new Date(x.deadline)-Date.now())/86400000):30;return (6-(x.priority||3))*2+(6-(x.difficulty||3))*1+1/days*10+(x.estimated_minutes||25)/60}
function renderCalendar(){const g=$('#calendarGrid'),now=new Date(),y=now.getFullYear(),m=now.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay();g.innerHTML='';for(let i=0;i<first;i++)g.innerHTML+='<div></div>';for(let d=1;d<=days;d++){const ds=new Date(y,m,d),key=ds.toDateString();const tasks=state.assignments.filter(x=>x.deadline&&new Date(x.deadline).toDateString()===key);const exams=state.exams.filter(x=>x.exam_at&&new Date(x.exam_at).toDateString()===key);g.innerHTML+=`<div><b>${d}</b>${tasks.slice(0,2).map(x=>`<div style="margin-top:7px;color:var(--gold2)">${esc(x.title)}</div>`).join('')}${exams.slice(0,1).map(x=>`<div style="margin-top:5px">⌁ ${esc(x.title)}</div>`).join('')}</div>`}}
function ensureButtons(){const specs=[['#exams','addExam','+ Add exam',addExam],['#classes','addClass','+ Add class',addClass],['#grades','addGradeTop','+ Add grade',addGrade],['#languages','addLanguage','+ Language',addLanguage],['#settings','exportData','Export data',exportData]];for(const [sel,id,text,fn] of specs){const sec=$(sel);if(!sec||$('#'+id))continue;const b=document.createElement('button');b.id=id;b.textContent=text;b.onclick=fn;const h=sec.querySelector('h2');h?.parentElement?.appendChild(b)}}
async function insert(table,row){const user=await requireUser();if(!user)return false;if(user.guest){const item={id:uid(),...row};state[table].push(item);saveGuest();renderAll();toast('Saved on this device');return true}const {error}=await sb.from(table).insert({...row,user_id:user.id});if(error){toast(error.message);return false}await loadData();toast('Saved to cloud');return true}
async function update(table,id,row){const user=await requireUser();if(!user)return;if(user.guest){const i=state[table].findIndex(x=>x.id===id);if(i<0)return;state[table][i]={...state[table][i],...row};saveGuest();renderAll();toast('Updated');return}const {error}=await sb.from(table).update(row).eq('id',id).eq('user_id',user.id);if(error)toast(error.message);else{await loadData();toast('Updated')}}
async function remove(table,id){const user=await requireUser();if(!user)return;if(user.guest){state[table]=state[table].filter(x=>x.id!==id);saveGuest();renderAll();toast('Deleted');return}const {error}=await sb.from(table).delete().eq('id',id).eq('user_id',user.id);if(error)toast(error.message);else{await loadData();toast('Deleted')}}
async function addAssignment(){const title=prompt('Assignment title');if(!title)return;const deadline=prompt('Deadline (YYYY-MM-DD HH:MM) or blank');const est=prompt('Estimated minutes','30');const difficulty=prompt('Difficulty 1–5','3');const priority=prompt('Priority 1–5','3');await insert('assignments',{title,deadline:deadline?new Date(deadline).toISOString():null,estimated_minutes:Number(est)||30,difficulty:Number(difficulty)||3,priority:Number(priority)||3,status:'todo'})}
async function addNote(){const title=prompt('Note title');if(!title)return;const body=prompt('Note body')||'';await insert('notes',{title,body})}
async function addExam(){const title=prompt('Exam title');if(!title)return;const when=prompt('Exam date/time (YYYY-MM-DD HH:MM)');if(!when)return;await insert('exams',{title,exam_at:new Date(when).toISOString()})}
async function addGrade(){const title=prompt('Grade title');if(!title)return;const score=prompt('Score');const max=prompt('Max score','100');const weight=prompt('Weight','1');await insert('grades',{title,score:Number(score),max_score:Number(max),weight:Number(weight)})}
async function addVocab(){const word=prompt('Word');if(!word)return;const meaning=prompt('Meaning');const example=prompt('Example sentence')||'';await insert('vocabulary',{language_code:prompt('Language code','en'),word,meaning,example})}
async function addLanguage(){const code=prompt('Language code (ja/en/zh/ko/es)');if(!code)return;await insert('language_profiles',{language_code:code,level:prompt('Current level','beginner'),target_level:prompt('Target level','intermediate')})}
async function addClass(){if(!state.subjects.length){const name=prompt('Subject name');if(!name)return;await insert('subjects',{name});return}const sub=state.subjects.map((s,i)=>`${i+1}. ${s.name}`).join('\n');const n=Number(prompt(sub));const subject=state.subjects[n-1];if(!subject)return;await insert('classes',{subject_id:subject.id,teacher:prompt('Teacher')||'',room:prompt('Room')||'',weekday:Number(prompt('Weekday 0=Sun…6=Sat','1')),start_time:prompt('Start time HH:MM')||null,end_time:prompt('End time HH:MM')||null})}
function reviewVocab(){const v=state.vocab.filter(x=>!x.due_at||new Date(x.due_at)<=new Date()).slice(0,10);const box=$('#vocabReview');box.innerHTML=v.length?v.map(x=>`<div class="item"><b>${esc(x.word)}</b><button onclick="this.previousElementSibling.textContent='${esc(x.meaning||'No meaning')}';this.remove()">Reveal</button></div>`).join(''):'<p class="muted">Nothing due right now.</p>'}
async function completeAssignment(id){const x=state.assignments.find(a=>a.id===id);if(x)await update('assignments',id,{status:x.status==='completed'?'todo':'completed'})}
async function editAssignment(id){const x=state.assignments.find(a=>a.id===id);if(!x)return;const title=prompt('Title',x.title);if(title)await update('assignments',id,{title})}
async function editNote(id){const x=state.notes.find(n=>n.id===id);if(!x)return;const title=prompt('Title',x.title);const body=prompt('Body',x.body||'');await update('notes',id,{title:title||x.title,body:body??x.body,updated_at:new Date().toISOString()})}
async function pinNote(id){const x=state.notes.find(n=>n.id===id);if(x)await update('notes',id,{pinned:!x.pinned,updated_at:new Date().toISOString()})}
function wireEvents(){document.addEventListener('click',e=>{const a=e.target.closest('[data-act]');if(!a)return;const host=a.closest('[data-id]');if(!host)return;const id=host.dataset.id,act=a.dataset.act;if(location.hash==='#assignments'){if(act==='done')completeAssignment(id);if(act==='edit')editAssignment(id);if(act==='delete')remove('assignments',id)}else if(location.hash==='#notes'){if(act==='edit')editNote(id);if(act==='pin')pinNote(id);if(act==='delete')remove('notes',id)}else if(location.hash==='#exams'&&act==='delete')remove('exams',id)});document.addEventListener('click',e=>{const g=e.target.closest('[data-grade]');if(g)remove('grades',g.dataset.grade);const v=e.target.closest('[data-vocab]');if(v)remove('vocabulary',v.dataset.vocab)});$('#addAssignment').onclick=addAssignment;$('#addNote').onclick=addNote;$('#plan').onclick=async()=>{renderTempo();await saveTempoPlan()}}
async function saveTempoPlan(){const user=await requireUser();if(!user)return;const items=state.assignments.filter(x=>x.status!=='completed').sort((a,b)=>scoreTask(b)-scoreTask(a));if(user.guest){const plan={id:uid(),plan_date:new Date().toISOString().slice(0,10),total_minutes:items.reduce((s,x)=>s+(x.estimated_minutes||25),0)};state.plans.unshift(plan);saveGuest();renderAll();toast('Tempo plan saved on this device');return}const {data:plan,error}=await sb.from('tempo_plans').insert({user_id:user.id,plan_date:new Date().toISOString().slice(0,10),total_minutes:items.reduce((s,x)=>s+(x.estimated_minutes||25),0)}).select().single();if(error){toast(error.message);return}const tasks=items.slice(0,20).map((x,i)=>({plan_id:plan.id,assignment_id:x.id,title:x.title,estimated_minutes:x.estimated_minutes||25,priority:x.priority||3,sort_order:i}));if(tasks.length)await sb.from('tempo_tasks').insert(tasks);toast('Tempo plan saved');await loadData()}
async function finishTimer(){const planned=Math.round((1500-seconds)/60);if(planned<=0)return;await insert('sessions',{started_at:new Date(Date.now()-planned*60000).toISOString(),ended_at:new Date().toISOString(),planned_minutes:25,actual_minutes:planned,session_type:'focus'})}
let seconds=1500,timer=null;function paintTimer(){$('#timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
$('#start').onclick=()=>{if(timer)return;timer=setInterval(async()=>{seconds=Math.max(0,seconds-1);paintTimer();if(!seconds){clearInterval(timer);timer=null;await finishTimer();seconds=1500;paintTimer();toast('Focus session saved')}},1000)};$('#reset').onclick=()=>{clearInterval(timer);timer=null;seconds=1500;paintTimer()};
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='school-os-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
$('#add').onclick=()=>{const id=location.hash.slice(1);if(id==='assignments')addAssignment();else if(id==='notes')addNote();else if(id==='exams')addExam();else if(id==='grades')addGrade();else if(id==='classes')addClass();else if(id==='languages')addLanguage();else addAssignment()};
ensureButtons();wireEvents();navRoute();paintTimer();init();