const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:'Good morning.',assignments:'Assignments',calendar:'Calendar',notes:'Notes',study:'Study',tempo:'Tempo',classes:'Classes',grades:'Grades',exams:'Exams',languages:'Languages',settings:'Settings'};
const tables=['subjects','assignments','exams','notes','study_sessions','classes','grades','tempo_plans','vocabulary','flashcard_decks','goals','habits','notifications'];
const guestKey='school-os-guest-v2';
let sb=null,state={user:null,assignments:[],exams:[],notes:[],sessions:[],classes:[],subjects:[],grades:[],plans:[],vocab:[],decks:[],goals:[],habits:[],notifications:[]};
let calendarDate=new Date(),seconds=1500,timer=null,timerStart=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const fmt=d=>d?new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'No date';
const dateOnly=d=>d?new Date(d).toISOString().slice(0,10):'';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function guestData(){try{return JSON.parse(localStorage.getItem(guestKey)||'{}')}catch{return {}}}
function saveGuest(){localStorage.setItem(guestKey,JSON.stringify(Object.fromEntries(tables.map(t=>[t,state[t]||[]]))))}
function guestLoad(){const d=guestData();for(const t of tables)state[t]=Array.isArray(d[t])?d[t]:[];renderAll()}
async function currentUser(){return state.user||{id:'guest',guest:true}}
function subjectName(id){return state.subjects.find(s=>s.id===id)?.name||''}
async function load(table,order){let q=sb.from(table).select('*');if(order)q=q.order(order,{ascending:false});const {data,error}=await q.limit(300);if(error)throw error;return data||[]}
async function loadData(){try{const [subjects,assignments,exams,notes,sessions,classes,grades,plans,vocab,decks,goals,habits,notifications]=await Promise.all([load('subjects'),load('assignments','deadline'),load('exams','exam_at'),load('notes','updated_at'),load('study_sessions','started_at'),load('classes'),load('grades','graded_at'),load('tempo_plans','plan_date'),load('vocabulary','created_at'),load('flashcard_decks','created_at'),load('goals','target_date'),load('habits'),load('notifications','created_at')]);Object.assign(state,{subjects,assignments,exams,notes:notes.filter(n=>!n.deleted_at),sessions,classes,grades,plans,vocab,decks,goals,habits,notifications});renderAll()}catch(e){console.error(e);toast('Could not load cloud data. '+e.message)}}
async function insert(table,row){const u=await currentUser();if(u.guest){state[table].push({id:uid(),...row});saveGuest();renderAll();toast('Saved on this device');return true}const {error}=await sb.from(table).insert({...row,user_id:u.id});if(error){toast(error.message);return false}await loadData();toast('Saved');return true}
async function update(table,id,row){const u=await currentUser();if(u.guest){const i=state[table].findIndex(x=>x.id===id);if(i>=0){state[table][i]={...state[table][i],...row};saveGuest();renderAll();toast('Updated')}return}const {error}=await sb.from(table).update(row).eq('id',id).eq('user_id',u.id);if(error)toast(error.message);else{await loadData();toast('Updated')}}
async function remove(table,id){const u=await currentUser();if(u.guest){state[table]=state[table].filter(x=>x.id!==id);saveGuest();renderAll();toast('Deleted');return}const {error}=await sb.from(table).delete().eq('id',id).eq('user_id',u.id);if(error)toast(error.message);else{await loadData();toast('Deleted')}}
function navRoute(){let id=location.hash.slice(1)||'dashboard';if(!titles[id])id='dashboard';$$('main section').forEach(s=>s.style.display=s.id===id?'block':'none');$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));$('#title').textContent=titles[id];if(id==='calendar')renderCalendar();if(id==='tempo')renderTempo()}
function renderAll(){renderDashboard();renderAssignments();renderNotes();renderStudy();renderCalendar();renderTempo();renderClasses();renderGrades();renderExams();renderLanguages();updateAccountUI();navRoute()}
function renderDashboard(){const open=state.assignments.filter(x=>x.status!=='completed'),done=state.assignments.length-open.length,mins=state.sessions.reduce((s,x)=>s+Number(x.actual_minutes||0),0),pct=state.assignments.length?Math.round(done/state.assignments.length*100):0;$('#tasks').textContent=open.length;$('#navTasks').textContent=open.length;$('#exams').textContent=state.exams.length;$('#notes').textContent=state.notes.length;$('#study').textContent=mins+'m';$('#progress').textContent=pct+'%';$('#progressBar').style.width=pct+'%';$('#progressText').textContent=state.assignments.length?`${done} of ${state.assignments.length} assignments completed`:'Add your first assignment to start tracking progress.';$('#taskSub').textContent=open.length?`${open.length} still to finish`:'Everything is clear';$('#examSub').textContent=state.exams.length?`${state.exams.length} scheduled`:'No exams scheduled';const next=[...open].sort((a,b)=>(new Date(a.deadline||'2999')-new Date(b.deadline||'2999')))[0];$('#next').textContent=next?.title||'Nothing urgent';$('#nextMeta').textContent=next?.deadline?'Due '+fmt(next.deadline):'You are caught up.';$('#upcoming').innerHTML=[...open].sort((a,b)=>(new Date(a.deadline||'2999')-new Date(b.deadline||'2999'))).slice(0,6).map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${esc(subjectName(x.subject_id)||'General')} · ${x.estimated_minutes||25} min</small></div><span class="date-label">${x.deadline?fmt(x.deadline):'No deadline'}</span></div>`).join('')||'<div class="empty"><span>✓</span><p>No open assignments.</p></div>';$('#recent').innerHTML=state.notes.slice(0,6).map(x=>`<div class="item"><div><b>${esc(x.title||'Untitled')}</b><small>${esc((x.body||'').slice(0,70))}</small></div></div>`).join('')||'<div class="empty"><span>✎</span><p>Your notes will appear here.</p></div>'}
function assignmentMatches(x){const q=($('#assignmentSearch')?.value||'').toLowerCase(),filter=$('#assignmentFilter')?.value||'all',overdue=x.status!=='completed'&&x.deadline&&new Date(x.deadline)<new Date();if(q&&!(`${x.title} ${subjectName(x.subject_id)}`.toLowerCase().includes(q)))return false;if(filter==='open'&&x.status==='completed')return false;if(filter==='completed'&&x.status!=='completed')return false;if(filter==='overdue'&&!overdue)return false;return true}
function renderAssignments(){const box=$('#assignmentList');if(!box)return;let items=state.assignments.filter(assignmentMatches);const sort=$('#assignmentSort')?.value||'deadline';items.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='priority'?(b.priority||3)-(a.priority||3):new Date(a.deadline||'2999')-new Date(b.deadline||'2999'));box.innerHTML=items.length?items.map(x=>{const overdue=x.status!=='completed'&&x.deadline&&new Date(x.deadline)<new Date();return `<div class="item assignment-item ${x.status==='completed'?'completed':''}" data-id="${x.id}"><button class="check ${x.status==='completed'?'checked':''}" data-act="done">${x.status==='completed'?'✓':''}</button><div class="grow"><b>${esc(x.title)}</b><small>${esc(subjectName(x.subject_id)||'General')} · ${x.estimated_minutes||25} min · ${x.difficulty||3}/5 difficulty</small></div><span class="priority p${x.priority||3}">P${x.priority||3}</span><span class="date-label ${overdue?'overdue':''}">${x.deadline?fmt(x.deadline):'No deadline'}</span><div class="item-actions"><button class="ghost mini" data-act="edit">Edit</button><button class="ghost mini danger" data-act="delete">Delete</button></div></div>`}).join(''):'<div class="empty large"><span>✓</span><h3>No assignments here</h3><p>Try changing the filter or add something you need to finish.</p></div>'}
function renderNotes(){const grid=$('#notesGrid');if(!grid)return;const q=($('#noteSearch')?.value||'').toLowerCase();let notes=state.notes.filter(n=>`${n.title} ${n.body}`.toLowerCase().includes(q));if($('#showPinned')?.dataset.active==='1')notes=notes.filter(n=>n.pinned);grid.innerHTML=notes.length?notes.map(x=>`<article class="card note-card" data-id="${x.id}"><div class="note-top"><span class="pill">${x.pinned?'★ PINNED':'NOTE'}</span><button class="dots" data-act="delete">×</button></div><h3>${esc(x.title||'Untitled')}</h3><p>${esc((x.body||'').slice(0,260))}${(x.body||'').length>260?'…':''}</p><div class="note-footer"><small>${x.updated_at?fmt(x.updated_at):'Saved'}</small><span><button class="ghost mini" data-act="edit">Edit</button><button class="ghost mini" data-act="pin">${x.pinned?'Unpin':'Pin'}</button></span></div></article>`).join(''):'<div class="card empty large"><span>✎</span><h3>No notes found</h3><p>Create a note for class, revision or whatever brilliant thought just escaped your brain.</p></div>'}
function renderStudy(){const weekStart=Date.now()-7*86400000,week=state.sessions.filter(x=>new Date(x.started_at||0).getTime()>=weekStart).reduce((s,x)=>s+Number(x.actual_minutes||0),0);$('#weekMinutes').textContent=week+' min';$('#studyHistory').innerHTML=state.sessions.slice(0,10).map(x=>`<div class="item"><div><b>${x.session_type==='focus'?'Focus':'Study'}</b><small>${x.started_at?fmt(x.started_at):''}</small></div><span>${x.actual_minutes||0} min</span></div>`).join('')||'<div class="empty"><span>◷</span><p>Complete your first focus session.</p></div>';$('#timerStatus').textContent=timer?'Focus mode is running.':'Ready when you are.'}
function renderClasses(){const box=$('#classList');if(!box)return;box.innerHTML=state.classes.length?state.classes.map(x=>`<div class="card class-card"><div class="class-day">${x.weekday==null?'CLASS':['SUN','MON','TUE','WED','THU','FRI','SAT'][x.weekday]}</div><h3>${esc(subjectName(x.subject_id)||'Class')}</h3><p>${esc(x.teacher||'Teacher not set')}</p><div class="class-meta">${esc(x.room||'Room not set')} · ${esc(x.start_time||'')} ${x.end_time?'– '+esc(x.end_time):''}</div><button class="ghost mini danger" data-class="${x.id}">Remove</button></div>`).join(''):'<div class="card empty large"><span>▤</span><h3>No classes yet</h3><p>Add your timetable once and use it across School OS.</p></div>'}
function renderGrades(){const avg=state.grades.reduce((s,g)=>s+(g.score!=null&&g.max_score?Number(g.score)/Number(g.max_score)*100*Number(g.weight||1):0),0),weights=state.grades.reduce((s,g)=>s+Number(g.weight||1),0);$('#gradeAverage').textContent=weights?Math.round(avg/weights)+'%':'—';$('#gradeList').innerHTML=state.grades.map(g=>`<div class="item"><div><b>${esc(g.title)}</b><small>${esc(subjectName(g.subject_id)||'General')} · weight ${g.weight||1}</small></div><span>${g.score??'—'} / ${g.max_score??'—'} <button class="ghost mini danger" data-grade="${g.id}">×</button></span></div>`).join('')||'<div class="empty"><p>No grades yet.</p></div>'}
function renderExams(){const box=$('#examList');box.innerHTML=state.exams.length?state.exams.map(x=>{const days=Math.ceil((new Date(x.exam_at)-Date.now())/86400000);return `<div class="item exam-item" data-id="${x.id}"><div class="exam-count"><b>${days>=0?days:'—'}</b><small>days</small></div><div class="grow"><b>${esc(x.title)}</b><small>${esc(subjectName(x.subject_id)||'General')} · ${fmt(x.exam_at)}</small></div><button class="ghost mini danger" data-act="delete">Delete</button></div>`}).join(''):'<div class="empty large"><span>⌁</span><h3>No exams scheduled</h3><p>Add an exam so Tempo can account for it.</p></div>'}
function renderLanguages(){const count=$('#vocabCount');if(count)count.textContent=`${state.vocab.length} saved words`;const list=$('#vocabList');if(list)list.innerHTML=state.vocab.slice(0,15).map(v=>`<div class="item"><div><b>${esc(v.word)}</b><small>${esc(v.meaning||'')}</small></div><button class="ghost mini danger" data-vocab="${v.id}">×</button></div>`).join('')||'<div class="empty"><p>No vocabulary yet.</p></div>'}
function scoreTask(x){const days=x.deadline?Math.max(.15,(new Date(x.deadline)-Date.now())/86400000):30;return (6-(x.priority||3))*2+(6-(x.difficulty||3))+1/days*12+(x.estimated_minutes||25)/60}
function renderTempo(){const items=state.assignments.filter(x=>x.status!=='completed').sort((a,b)=>scoreTask(b)-scoreTask(a));$('#tempoMinutes').textContent=items.reduce((s,x)=>s+Number(x.estimated_minutes||25),0)+'m';$('#planList').innerHTML=items.slice(0,12).map((x,i)=>`<div class="item tempo-item"><span class="rank">${i+1}</span><div class="grow"><b>${esc(x.title)}</b><small>${x.deadline?'Due '+fmt(x.deadline):'No deadline'} · ${x.estimated_minutes||25} min</small></div><span class="priority p${x.priority||3}">P${x.priority||3}</span></div>`).join('')||'<div class="empty large"><span>✦</span><h3>Your queue is empty</h3><p>Add assignments and Tempo will turn them into a prioritized plan.</p></div>'}
function renderCalendar(){const g=$('#calendarGrid');if(!g)return;const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();$('#calendarTitle').textContent=calendarDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});g.innerHTML='';for(let i=0;i<first;i++)g.innerHTML+='<div class="cal-day empty-day"></div>';for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,today=new Date().toDateString()===new Date(y,m,d).toDateString(),task=state.assignments.filter(x=>x.deadline&&dateOnly(x.deadline)===key),exams=state.exams.filter(x=>x.exam_at&&dateOnly(x.exam_at)===key);g.innerHTML+=`<div class="cal-day ${today?'today':''}"><span class="day-num">${d}</span>${task.slice(0,2).map(x=>`<span class="cal-event task-event">${esc(x.title)}</span>`).join('')}${exams.slice(0,1).map(x=>`<span class="cal-event exam-event">⌁ ${esc(x.title)}</span>`).join('')}</div>`}}
function updateAccountUI(){const signed=!!state.user;$('#account').textContent=signed?'Sign out':'Guest Mode · Sign in';$('#syncStatus').textContent=signed?'Cloud sync is active for this account.':'Guest mode saves your workspace on this device.';$('#settingsAccount').textContent=signed?'Sign out':'Sign in / create account'}
function openModal(title,body,submit='Save'){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="dots" data-close>×</button></div><form id="activeForm"><div class="form-body">${body}</div><div class="modal-actions"><button type="button" class="ghost" data-close>Cancel</button><button class="primary" type="submit">${submit}</button></div></form></div></div>`;root.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);root.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()};return root.querySelector('#activeForm')}
function closeModal(){ $('#modalRoot').innerHTML='' }
function input(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function selectSubject(){return `<label>Subject<select name="subject_id"><option value="">General</option>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label>`}
async function addAssignment(){const f=openModal('New assignment',input('Title','title','','text','required')+selectSubject()+input('Deadline','deadline','','datetime-local')+`<div class="form-grid">${input('Estimated minutes','estimated_minutes','30','number','min="5"')}<label>Difficulty<select name="difficulty"><option value="1">1 · Easy</option><option value="2">2</option><option value="3" selected>3 · Normal</option><option value="4">4</option><option value="5">5 · Hard</option></select></label></div><label>Priority<select name="priority"><option value="1">1 · Highest</option><option value="2">2</option><option value="3" selected>3 · Normal</option><option value="4">4</option><option value="5">5 · Low</option></select></label>`);f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('assignments',{title:d.get('title'),subject_id:d.get('subject_id')||null,deadline:d.get('deadline')?new Date(d.get('deadline')).toISOString():null,estimated_minutes:Number(d.get('estimated_minutes'))||30,difficulty:Number(d.get('difficulty'))||3,priority:Number(d.get('priority'))||3,status:'todo'});closeModal()}}
async function addNote(){const f=openModal('New note',input('Title','title','','text','required')+`<label>Note body<textarea name="body" rows="8" placeholder="Write your notes…"></textarea></label>`);f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('notes',{title:d.get('title'),body:d.get('body')||''});closeModal()}}
async function addExam(){const f=openModal('Add exam',input('Exam name','title','','text','required')+selectSubject()+input('Date & time','exam_at','','datetime-local','required'));f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('exams',{title:d.get('title'),subject_id:d.get('subject_id')||null,exam_at:new Date(d.get('exam_at')).toISOString()});closeModal()}}
async function addGrade(){const f=openModal('Add grade',input('Assessment','title','','text','required')+selectSubject()+`<div class="form-grid">${input('Score','score','','number','required')}${input('Max score','max_score','100','number','required')}</div>${input('Weight','weight','1','number','min="0.1" step="0.1"')}`);f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('grades',{title:d.get('title'),subject_id:d.get('subject_id')||null,score:Number(d.get('score')),max_score:Number(d.get('max_score'))||100,weight:Number(d.get('weight'))||1});closeModal()}}
async function addVocab(){const f=openModal('Add vocabulary',input('Word','word','','text','required')+input('Meaning','meaning')+`<label>Example sentence<textarea name="example" rows="3"></textarea></label>`+input('Language code','language_code','en'));f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('vocabulary',{word:d.get('word'),meaning:d.get('meaning')||'',example:d.get('example')||'',language_code:d.get('language_code')||'en'});closeModal()}}
async function addLanguage(){const f=openModal('Add language',input('Language code','language_code','ja','text','required')+input('Current level','level','beginner')+input('Target level','target_level','intermediate'));f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await insert('language_profiles',{language_code:d.get('language_code'),level:d.get('level'),target_level:d.get('target_level')});closeModal()}}
async function addClass(){const f=openModal('Add class',state.subjects.length?selectSubject()+input('Teacher','teacher')+input('Room','room')+`<div class="form-grid"><label>Day<select name="weekday"><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="0">Sunday</option></select></label>${input('Start','start_time','','time')}</div>${input('End','end_time','','time')}`:input('Subject name','subject_name','','text','required'));f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);let subjectId=d.get('subject_id');if(!subjectId&&d.get('subject_name')){const name=d.get('subject_name');await insert('subjects',{name});subjectId=state.subjects.find(s=>s.name===name)?.id}if(subjectId)await insert('classes',{subject_id:subjectId,teacher:d.get('teacher')||'',room:d.get('room')||'',weekday:Number(d.get('weekday')),start_time:d.get('start_time')||null,end_time:d.get('end_time')||null});closeModal()}}
async function editAssignment(id){const x=state.assignments.find(a=>a.id===id);if(!x)return;const f=openModal('Edit assignment',input('Title','title',x.title,'text','required')+selectSubject()+input('Deadline','deadline',x.deadline?new Date(x.deadline).toISOString().slice(0,16):'','datetime-local')+input('Estimated minutes','estimated_minutes',x.estimated_minutes||30,'number','min="5"'));f.querySelector('[name=subject_id]').value=x.subject_id||'';f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await update('assignments',id,{title:d.get('title'),subject_id:d.get('subject_id')||null,deadline:d.get('deadline')?new Date(d.get('deadline')).toISOString():null,estimated_minutes:Number(d.get('estimated_minutes'))||25});closeModal()}}
async function editNote(id){const x=state.notes.find(n=>n.id===id);if(!x)return;const f=openModal('Edit note',input('Title','title',x.title||'Untitled','text','required')+`<label>Note body<textarea name="body" rows="10">${esc(x.body||'')}</textarea></label>`);f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);await update('notes',id,{title:d.get('title'),body:d.get('body'),updated_at:new Date().toISOString()});closeModal()}}
async function signIn(){if(state.user){await sb.auth.signOut();return}const f=openModal('Sign in to sync',input('Email','email','','email','required')+input('Password','password','','password','required minlength="6"')+'<p class="form-hint">New here? If the account does not exist, School OS can create it.</p>','Continue');f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);let r=await sb.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});if(r.error){const create=confirm('Account not found. Create this account?');if(create)r=await sb.auth.signUp({email:d.get('email'),password:d.get('password')})}if(r.error){toast(r.error.message);return}closeModal();if(r.data.session){state.user=r.data.user;await loadData();toast('Cloud sync enabled')}else toast('Account created. Check your email, then sign in.')}}
async function saveTempoPlan(){const items=state.assignments.filter(x=>x.status!=='completed').sort((a,b)=>scoreTask(b)-scoreTask(a));if(!items.length){toast('Add an assignment first');return}await insert('tempo_plans',{plan_date:new Date().toISOString().slice(0,10),total_minutes:items.reduce((s,x)=>s+Number(x.estimated_minutes||25),0)})}
async function finishTimer(){const actual=Math.max(1,Math.round((Date.now()-timerStart)/60000));await insert('study_sessions',{started_at:new Date(timerStart).toISOString(),ended_at:new Date().toISOString(),planned_minutes:25,actual_minutes:actual,session_type:'focus'});seconds=1500;paintTimer()}
function paintTimer(){$('#timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
function startTimer(){if(timer)return;timerStart=Date.now();timer=setInterval(async()=>{seconds--;paintTimer();if(seconds<=0){clearInterval(timer);timer=null;await finishTimer();toast('Focus session saved');renderStudy()}},1000);renderStudy()}
function resetTimer(){clearInterval(timer);timer=null;seconds=1500;paintTimer();renderStudy()}
function exportData(){const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),school_os:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='school-os-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function wire(){document.addEventListener('click',async e=>{const act=e.target.closest('[data-act]');if(act){const host=act.closest('[data-id]');if(host){const id=host.dataset.id;if(location.hash==='#assignments'||!location.hash){if(act.dataset.act==='done')await update('assignments',id,{status:state.assignments.find(x=>x.id===id)?.status==='completed'?'todo':'completed'});if(act.dataset.act==='edit')editAssignment(id);if(act.dataset.act==='delete'&&confirm('Delete this assignment?'))remove('assignments',id)}else if(location.hash==='#notes'){if(act.dataset.act==='edit')editNote(id);if(act.dataset.act==='pin'){const x=state.notes.find(n=>n.id===id);if(x)update('notes',id,{pinned:!x.pinned,updated_at:new Date().toISOString()})}if(act.dataset.act==='delete'&&confirm('Delete this note?'))remove('notes',id)}else if(location.hash==='#exams'&&act.dataset.act==='delete'&&confirm('Delete this exam?'))remove('exams',id)}}const g=e.target.closest('[data-grade]');if(g&&confirm('Delete this grade?'))remove('grades',g.dataset.grade);const v=e.target.closest('[data-vocab]');if(v&&confirm('Delete this word?'))remove('vocabulary',v.dataset.vocab);const c=e.target.closest('[data-class]');if(c&&confirm('Remove this class?'))remove('classes',c.dataset.class)});
$('#addAssignment').onclick=addAssignment;$('#addNote').onclick=addNote;$('#addExam').onclick=addExam;$('#addGradeTop').onclick=addGrade;$('#addVocab').onclick=addVocab;$('#addLanguage').onclick=addLanguage;$('#addClass').onclick=addClass;$('#plan').onclick=saveTempoPlan;$('#add').onclick=()=>{const id=location.hash.slice(1);if(id==='notes')addNote();else if(id==='exams')addExam();else if(id==='grades')addGrade();else if(id==='classes')addClass();else if(id==='languages')addVocab();else addAssignment()};$('#dashboardAdd').onclick=addAssignment;$('#quickStudy').onclick=()=>{location.hash='#study';startTimer()};$('#start').onclick=startTimer;$('#reset').onclick=resetTimer;$$('.mode').forEach(b=>b.onclick=()=>{if(!timer){seconds=Number(b.dataset.min)*60;paintTimer();$$('.mode').forEach(x=>x.classList.toggle('active',x===b))}});$('#searchBtn').onclick=()=>{const f=openModal('Search School OS',`<label>Search<input id="globalSearch" autofocus placeholder="Assignments, notes, exams…"></label><div id="globalResults" class="search-results"></div>`,'Close');f.querySelector('button[type=submit]').onclick=closeModal;f.onsubmit=e=>e.preventDefault();const inp=f.querySelector('#globalSearch'),out=f.querySelector('#globalResults');inp.oninput=()=>{const q=inp.value.toLowerCase();const rows=[...state.assignments.map(x=>({type:'Assignment',title:x.title,hash:'#assignments'})),...state.notes.map(x=>({type:'Note',title:x.title,hash:'#notes'})),...state.exams.map(x=>({type:'Exam',title:x.title,hash:'#exams'}))].filter(x=>x.title?.toLowerCase().includes(q)).slice(0,10);out.innerHTML=rows.map(x=>`<a href="${x.hash}" data-close><small>${x.type}</small><b>${esc(x.title)}</b></a>`).join('')||'<p class="muted">No matches.</p>';out.querySelectorAll('[data-close]').forEach(a=>a.onclick=closeModal)};inp.focus()};$('#account').onclick=signIn;$('#settingsAccount').onclick=signIn;$('#exportData').onclick=exportData;$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('#todayMonth').onclick=()=>{calendarDate=new Date();renderCalendar()};$('#calendarAdd').onclick=addAssignment;$('#assignmentSearch').oninput=renderAssignments;$('#assignmentFilter').onchange=renderAssignments;$('#assignmentSort').onchange=renderAssignments;$('#noteSearch').oninput=renderNotes;$('#showPinned').onclick=e=>{e.currentTarget.dataset.active=e.currentTarget.dataset.active==='1'?'0':'1';e.currentTarget.classList.toggle('active');renderNotes()}}
async function init(){if(!window.SCHOOL_OS_SUPABASE_URL||!window.SCHOOL_OS_SUPABASE_KEY){guestLoad();return}sb=window.supabase.createClient(window.SCHOOL_OS_SUPABASE_URL,window.SCHOOL_OS_SUPABASE_KEY);const {data:{session}}=await sb.auth.getSession();state.user=session?.user||null;sb.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;updateAccountUI();if(state.user)loadData();else guestLoad()});if(state.user)await loadData();else guestLoad()}
$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});window.addEventListener('hashchange',navRoute);wire();navRoute();paintTimer();init();