/* School OS Premium Feature Layer
   Adds the product features that sit above the core workspace: AI assistant, flashcards,
   quizzes, goals, analytics, files, wellbeing, quick capture, trash, onboarding and global search.
   Works in guest mode first; cloud sync can be wired to matching Supabase tables later.
*/
(()=>{
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $2=s=>document.querySelector(s);
const KEY='school-os-premium-v1';
const loadP=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const P=loadP();
const saveP=()=>localStorage.setItem(KEY,JSON.stringify(P));
const arr=(k)=>P[k]||(P[k]=[]);
const toast2=m=>typeof toast==='function'?toast(m):alert(m);
function modal(title,body,buttons=''){$2('#modalRoot').innerHTML=`<div class="os-modal-backdrop" id="osBackdrop"><div class="os-modal"><div class="os-modal-head"><div><small>School OS</small><h2>${title}</h2></div><button class="os-close" id="osClose">×</button></div><div class="os-modal-body">${body}</div>${buttons?`<div class="os-modal-actions">${buttons}</div>`:''}</div></div>`;$2('#osClose').onclick=closeModal;$2('#osBackdrop').onclick=e=>{if(e.target.id==='osBackdrop')closeModal()}}
function closeModal(){$2('#modalRoot').innerHTML=''}
function addNav(id,label,icon,group='TOOLS'){const navs=document.querySelectorAll('aside nav');let nav=navs[0];if(group==='TOOLS'){let lab=[...document.querySelectorAll('.workspace-label')].find(x=>x.textContent==='TOOLS');if(!lab){lab=document.createElement('div');lab.className='workspace-label second';lab.textContent='TOOLS';document.querySelector('aside').insertBefore(lab,document.querySelector('aside .bottom'));nav=document.createElement('nav');document.querySelector('aside').insertBefore(nav,document.querySelector('aside .bottom'))}else nav=lab.nextElementSibling}if(!document.querySelector(`a[href="#${id}"]`))nav.insertAdjacentHTML('beforeend',`<a href="#${id}">${icon} <span>${label}</span></a>`)}
function section(id,html){if($2('#'+id))return;document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="${id}" class="page premium-page">${html}</section>`)}
function bootUI(){
 addNav('assistant','AI Study','✦');addNav('flashcards','Flashcards','▣');addNav('quizzes','Quiz Center','?');addNav('goals','Goals','◎');addNav('analytics','Analytics','▥');addNav('files','Files','□');addNav('wellbeing','Wellbeing','♡');
 titles.assistant='AI Study Assistant';titles.flashcards='Flashcards';titles.quizzes='Quiz Center';titles.goals='Goals';titles.analytics='Analytics';titles.files='Files';titles.wellbeing='Wellbeing';
 section('assistant',`<div class="page-head"><div><div class="eyebrow">STUDY INTELLIGENCE</div><h2>AI Study Assistant</h2><p>Explain, quiz, summarize and plan from the material you give it.</p></div></div><div class="ai-layout"><div class="card"><div class="eyebrow">ASK</div><textarea id="aiInput" class="big-input" placeholder="Paste a topic, notes, question or assignment..."></textarea><div class="ai-actions"><button class="primary" id="aiExplain">Explain it</button><button class="ghost" id="aiQuiz">Make practice questions</button><button class="ghost" id="aiSummary">Summarize</button><button class="ghost" id="aiPlan">Make a study plan</button></div></div><div class="card ai-output"><div class="row"><div><div class="eyebrow">RESPONSE</div><h3>Study with understanding</h3></div><span class="pill" id="aiStatus">Ready</span></div><div id="aiOutput" class="prose muted">Give the assistant some material to work with.</div></div></div>`);
 section('flashcards',`<div class="page-head"><div><div class="eyebrow">ACTIVE RECALL</div><h2>Flashcards</h2><p>Build decks manually or turn your notes into cards.</p></div><button class="primary" id="newDeck">+ New deck</button></div><div class="columns"><div class="card"><div class="row"><h3>Your decks</h3><button class="ghost" id="cardsFromNotes">From notes</button></div><div id="deckList"></div></div><div class="card" id="reviewCard"><div class="eyebrow">REVIEW</div><h3>Pick a deck</h3><p class="muted">Spaced repetition starts with a simple review queue.</p></div></div>`);
 section('quizzes',`<div class="page-head"><div><div class="eyebrow">PRACTICE</div><h2>Quiz Center</h2><p>Generate or write practice questions and review mistakes.</p></div><button class="primary" id="newQuiz">+ Create quiz</button></div><div id="quizList" class="quiz-list"></div>`);
 section('goals',`<div class="page-head"><div><div class="eyebrow">DIRECTION</div><h2>Goals & Habits</h2><p>Turn intentions into visible progress.</p></div><button class="primary" id="newGoal">+ Add goal</button></div><div class="columns"><div class="card"><div class="row"><h3>Goals</h3><span class="pill" id="goalCount">0</span></div><div id="goalList"></div></div><div class="card"><div class="row"><h3>Daily habits</h3><button class="ghost" id="newHabit">+ Habit</button></div><div id="habitList"></div></div></div>`);
 section('analytics',`<div class="page-head"><div><div class="eyebrow">INSIGHTS</div><h2>Analytics</h2><p>Understand where your time is actually going.</p></div></div><div class="stats"><div class="card stat"><span>Assignments done</span><b id="anDone">0</b><small>All time</small></div><div class="card stat"><span>Study minutes</span><b id="anMinutes">0</b><small>Recorded sessions</small></div><div class="card stat"><span>Completion</span><b id="anRate">0%</b><small>Assignment rate</small></div><div class="card stat"><span>Words learned</span><b id="anWords">0</b><small>Saved vocabulary</small></div></div><div class="columns"><div class="card"><h3>Workload</h3><div id="workloadChart" class="bars"></div></div><div class="card"><h3>Recommendations</h3><div id="recommendations" class="list"></div></div></div>`);
 section('files',`<div class="page-head"><div><div class="eyebrow">MATERIALS</div><h2>Files</h2><p>Keep worksheets, PDFs and reference material connected to school work.</p></div><label class="primary file-label">+ Add files<input id="filePicker" type="file" multiple hidden></label></div><div class="card"><div class="toolbar"><input id="fileSearch" class="search-input" placeholder="Search files…"></div><div id="fileList" class="file-list"></div></div>`);
 section('wellbeing',`<div class="page-head"><div><div class="eyebrow">BALANCE</div><h2>Wellbeing</h2><p>Track energy and workload without turning your life into a spreadsheet.</p></div></div><div class="columns"><div class="card"><h3>Today's check-in</h3><div class="wellbeing-options"><button data-energy="1">Low energy</button><button data-energy="2">Okay</button><button data-energy="3">Good</button><button data-energy="4">Great</button></div><textarea id="wellbeingNote" class="input" placeholder="Optional note"></textarea><button class="primary" id="saveWellbeing">Save check-in</button></div><div class="card"><div class="eyebrow">RECENT</div><h3>Your pattern</h3><div id="wellbeingHistory"></div></div></div>`);
 section('trash',`<div class="page-head"><div><div class="eyebrow">RECOVERY</div><h2>Recently Deleted</h2><p>Accidental deletion is one of humanity's oldest traditions.</p></div></div><div id="trashList" class="card list"></div>`);
 addNav('trash','Trash','⌫');titles.trash='Recently Deleted';
}
async function aiRequest(prompt,mode){const out=$2('#aiOutput'),status=$2('#aiStatus');status.textContent='Thinking…';out.classList.remove('muted');out.textContent='';try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,input:prompt})});const j=await r.json();if(!r.ok)throw new Error(j.error||'AI endpoint unavailable');out.innerHTML=esc2(j.text).replace(/\n/g,'<br>');status.textContent='Done'}catch(e){status.textContent='Offline';const fallback={explain:`Here is a study-first way to approach this:\n\n1. Identify the main idea.\n2. Explain it in your own words.\n3. Find one concrete example.\n4. Test yourself without looking.\n\nYour material:\n${prompt}`,summary:`Key material to review:\n\n${prompt.slice(0,1400)}\n\nTry reducing this to 3–5 facts you could explain from memory.`,quiz:`Practice questions:\n\n1. What is the main idea?\n2. Why does it matter?\n3. Give one example.\n4. What would happen if the key condition changed?\n5. Explain the topic without using your notes.`,plan:`Study plan:\n\n• 10 min: understand the core idea\n• 15 min: active recall\n• 10 min: practice questions\n• 5 min: review mistakes\n\nFocus on the weakest part first.`};out.innerHTML=esc2(fallback[mode]||fallback.explain).replace(/\n/g,'<br>')}}
function setupAI(){$2('#aiExplain').onclick=()=>aiRequest($2('#aiInput').value,'explain');$2('#aiQuiz').onclick=()=>aiRequest($2('#aiInput').value,'quiz');$2('#aiSummary').onclick=()=>aiRequest($2('#aiInput').value,'summary');$2('#aiPlan').onclick=()=>aiRequest($2('#aiInput').value,'plan')}
function renderDecks(){const list=$2('#deckList');if(!list)return;const decks=arr('decks');list.innerHTML=decks.length?decks.map(d=>`<div class="item"><div><b>${esc2(d.name)}</b><small>${d.cards.length} cards · ${d.mastery||0}% mastery</small></div><button class="ghost mini" data-review="${d.id}">Review</button></div>`).join(''):'<div class="empty"><p>No decks yet. Create one from a topic or your notes.</p></div>'}
function newDeck(){modal('Create a deck',`<input id="deckName" class="input" placeholder="Deck name"><textarea id="deckSource" class="input" placeholder="Optional: paste notes or terms. One card per line as Front :: Back"></textarea>`,`<button class="ghost" id="cancelM">Cancel</button><button class="primary" id="saveDeck">Create deck</button>`);$2('#cancelM').onclick=closeModal;$2('#saveDeck').onclick=()=>{const name=$2('#deckName').value.trim();if(!name)return;const cards=$2('#deckSource').value.split('\n').map(x=>x.split('::')).filter(x=>x[0]?.trim()).map(x=>({id:uid(),front:x[0].trim(),back:(x[1]||'').trim(),level:0,next:Date.now()}));arr('decks').push({id:uid(),name,cards,mastery:0});saveP();closeModal();renderDecks();toast2('Deck created')}}
function reviewDeck(id){const d=arr('decks').find(x=>x.id===id);if(!d||!d.cards.length){toast2('This deck has no cards yet.');return}let i=0,revealed=false;const render=()=>{const c=d.cards[i%d.cards.length];$2('#reviewCard').innerHTML=`<div class="eyebrow">REVIEW · ${i+1}/${d.cards.length}</div><div class="flash-face"><h2>${esc2(revealed?c.back:c.front)}</h2></div><div class="row"><button class="ghost" id="reveal">${revealed?'Hide answer':'Reveal answer'}</button><div><button class="ghost" id="hard">Hard</button><button class="primary" id="easy">Got it</button></div></div>`;$2('#reveal').onclick=()=>{revealed=!revealed;render()};$2('#hard').onclick=()=>{c.level=Math.max(0,(c.level||0)-1);c.next=Date.now()+10*60000;i++;revealed=false;saveP();render()};$2('#easy').onclick=()=>{c.level=(c.level||0)+1;c.next=Date.now()+Math.min(30,2**c.level)*86400000;i++;revealed=false;saveP();render()}};render()}
function cardsFromNotes(){const notes=state.notes||[];if(!notes.length){toast2('Create notes first.');return}const cards=notes.slice(0,10).map(n=>({id:uid(),front:n.title,back:(n.body||'').slice(0,500),level:0,next:Date.now()}));arr('decks').push({id:uid(),name:'Notes review',cards,mastery:0});saveP();renderDecks();toast2('Deck created from your notes')}
function renderQuizzes(){const box=$2('#quizList');if(!box)return;box.innerHTML=arr('quizzes').map(q=>`<div class="card quiz-card"><div class="row"><div><span class="pill">${q.score==null?'PRACTICE':'SCORE '+q.score+'%'}</span><h3>${esc2(q.title)}</h3></div><button class="ghost mini" data-startquiz="${q.id}">Start</button></div><p>${q.questions.length} questions · ${esc2(q.topic||'General')}</p></div>`).join('')||'<div class="card empty large"><span>?</span><h3>No quizzes yet</h3><p>Create one from a topic or use the AI Study Assistant.</p></div>'}
function newQuiz(){modal('Create a quiz',`<input id="quizTitle" class="input" placeholder="Quiz title"><input id="quizTopic" class="input" placeholder="Topic"><textarea id="quizQs" class="input" placeholder="Question | answer\nQuestion | answer\nQuestion | answer"></textarea>`,`<button class="ghost" id="cancelM">Cancel</button><button class="primary" id="saveQuiz">Create quiz</button>`);$2('#cancelM').onclick=closeModal;$2('#saveQuiz').onclick=()=>{const qs=$2('#quizQs').value.split('\n').map(x=>x.split('|')).filter(x=>x[0]?.trim()).map(x=>({q:x[0].trim(),a:(x[1]||'').trim()}));if(!qs.length)return;arr('quizzes').push({id:uid(),title:$2('#quizTitle').value||'Practice quiz',topic:$2('#quizTopic').value,questions:qs});saveP();closeModal();renderQuizzes();toast2('Quiz created')}}
function startQuiz(id){const q=arr('quizzes').find(x=>x.id===id);if(!q)return;let i=0,score=0;const show=()=>{const x=q.questions[i];modal('Quiz',`<div class="eyebrow">QUESTION ${i+1} / ${q.questions.length}</div><h3>${esc2(x.q)}</h3><input id="quizAnswer" class="input" placeholder="Your answer">`,`<button class="primary" id="submitAnswer">${i===q.questions.length-1?'Finish':'Next'}</button>`);$2('#submitAnswer').onclick=()=>{const a=$2('#quizAnswer').value.trim().toLowerCase();if(a&&x.a&&a===x.a.toLowerCase())score++;i++;if(i<q.questions.length)show();else{q.score=Math.round(score/q.questions.length*100);saveP();closeModal();renderQuizzes();toast2(`Quiz complete: ${q.score}%`)}}};show()}
function renderGoals(){const goals=arr('goals'),habits=arr('habits');$2('#goalCount').textContent=goals.length;$2('#goalList').innerHTML=goals.map(g=>{const pct=Math.min(100,Math.round((g.current||0)/(g.target||1)*100));return `<div class="goal"><div class="row"><div><b>${esc2(g.title)}</b><small>${g.current||0} / ${g.target} ${esc2(g.unit||'')}</small></div><span>${pct}%</span></div><div class="progress-track"><i style="width:${pct}%"></i></div><button class="ghost mini" data-goal="${g.id}">+ Progress</button></div>`}).join('')||'<div class="empty"><p>No goals yet.</p></div>';$2('#habitList').innerHTML=habits.map(h=>`<div class="item"><div><b>${esc2(h.name)}</b><small>${h.streak||0} day streak</small></div><button class="primary mini" data-habit="${h.id}">Done today</button></div>`).join('')||'<div class="empty"><p>No habits yet.</p></div>'}
function newGoal(){modal('New goal',`<input id="goalTitle" class="input" placeholder="Goal"><div class="two"><input id="goalTarget" class="input" type="number" placeholder="Target"><input id="goalUnit" class="input" placeholder="Unit, e.g. minutes"></div>`,`<button class="ghost" id="cancelM">Cancel</button><button class="primary" id="saveGoal">Create</button>`);$2('#cancelM').onclick=closeModal;$2('#saveGoal').onclick=()=>{const target=Number($2('#goalTarget').value)||1;arr('goals').push({id:uid(),title:$2('#goalTitle').value||'New goal',target,current:0,unit:$2('#goalUnit').value});saveP();closeModal();renderGoals()}}
function newHabit(){modal('New habit',`<input id="habitName" class="input" placeholder="Habit, e.g. 20 min review">`,`<button class="ghost" id="cancelM">Cancel</button><button class="primary" id="saveHabit">Create</button>`);$2('#cancelM').onclick=closeModal;$2('#saveHabit').onclick=()=>{arr('habits').push({id:uid(),name:$2('#habitName').value||'New habit',streak:0,last:null});saveP();closeModal();renderGoals()}}
function renderAnalytics(){const done=(state.assignments||[]).filter(x=>x.status==='completed').length,total=(state.assignments||[]).length,mins=(state.sessions||[]).reduce((s,x)=>s+Number(x.actual_minutes||0),0);$2('#anDone').textContent=done;$2('#anMinutes').textContent=mins;$2('#anRate').textContent=(total?Math.round(done/total*100):0)+'%';$2('#anWords').textContent=(state.vocab||[]).length;const by={};(state.assignments||[]).forEach(x=>{const k=subjectName(x.subject_id)||'General';by[k]=(by[k]||0)+Number(x.estimated_minutes||25)});const max=Math.max(1,...Object.values(by));$2('#workloadChart').innerHTML=Object.entries(by).map(([k,v])=>`<div class="bar-row"><span>${esc2(k)}</span><i style="width:${Math.max(8,v/max*100)}%"></i><small>${v}m</small></div>`).join('')||'<p class="muted">Add assignments to see workload.</p>';$2('#recommendations').innerHTML=[total-done>5?'Your open workload is high. Let Tempo schedule the hardest deadlines first.': 'Your open workload looks manageable.',mins<60?'Try one focused session today.':'Keep your study sessions consistent.',(state.exams||[]).length?'Review your nearest exam before lower-priority work.':'Add your next exam so planning can account for it.'].map(x=>`<div class="item"><span>${x}</span></div>`).join('')}
function renderFiles(){const q=($2('#fileSearch')?.value||'').toLowerCase(),files=arr('files').filter(f=>f.name.toLowerCase().includes(q));$2('#fileList').innerHTML=files.map(f=>`<div class="item"><div><b>${esc2(f.name)}</b><small>${f.type||'File'} · ${Math.round(f.size/1024)} KB · added ${new Date(f.added).toLocaleDateString()}</small></div><button class="ghost mini danger" data-file="${f.id}">Remove</button></div>`).join('')||'<div class="empty"><p>No files yet.</p></div>'}
function renderWellbeing(){const h=arr('wellbeing');$2('#wellbeingHistory').innerHTML=h.slice(-7).reverse().map(x=>`<div class="item"><span>${['','Low energy','Okay','Good','Great'][x.energy]}</span><small>${new Date(x.date).toLocaleDateString()}</small></div>`).join('')||'<p class="muted">No check-ins yet.</p>'}
function renderTrash(){const deleted=arr('trash');$2('#trashList').innerHTML=deleted.map(x=>`<div class="item"><div><b>${esc2(x.title)}</b><small>${esc2(x.type)} · ${new Date(x.deleted).toLocaleString()}</small></div><button class="primary mini" data-restore="${x.id}">Restore</button></div>`).join('')||'<div class="empty large"><span>✓</span><h3>Trash is empty</h3></div>'}
function quickCapture(){modal('Quick capture',`<input id="capture" class="input" placeholder="Try: Math homework due Friday for 45 minutes"><div class="capture-hint">School OS will detect whether this is a task, note, exam or reminder.</div>`,`<button class="ghost" id="cancelM">Cancel</button><button class="primary" id="captureSave">Capture</button>`);$2('#cancelM').onclick=closeModal;$2('#captureSave').onclick=()=>{const text=$2('#capture').value.trim();if(!text)return;const lower=text.toLowerCase();if(/exam|test/.test(lower)){state.exams.push({id:uid(),title:text,exam_at:null});toast2('Captured as an exam')}else if(/homework|assignment|due|finish/.test(lower)){state.assignments.push({id:uid(),title:text,status:'todo',estimated_minutes:25,difficulty:3,priority:3,deadline:null});toast2('Captured as an assignment')}else{state.notes.push({id:uid(),title:'Quick capture',body:text,pinned:false});toast2('Captured as a note')}saveGuest();closeModal();renderAll()}}
function globalSearch(){modal('Search School OS',`<input id="globalQ" class="input" placeholder="Search assignments, notes, exams, vocabulary…"><div id="globalResults" class="list"></div>`);const run=()=>{const q=$2('#globalQ').value.toLowerCase();const rows=[...(state.assignments||[]).map(x=>['Assignment',x.title,'#assignments']),...(state.notes||[]).map(x=>['Note',x.title,'#notes']),...(state.exams||[]).map(x=>['Exam',x.title,'#exams']),...(state.vocab||[]).map(x=>['Word',x.word,'#languages'])].filter(x=>x[1].toLowerCase().includes(q)).slice(0,20);$2('#globalResults').innerHTML=rows.map(x=>`<a class="item search-result" href="${x[2]}"><span>${x[0]}</span><b>${esc2(x[1])}</b></a>`).join('')||'<p class="muted">No matches.</p>'};$2('#globalQ').oninput=run;run()}
function wirePremium(){setupAI();$2('#newDeck').onclick=newDeck;$2('#cardsFromNotes').onclick=cardsFromNotes;$2('#newQuiz').onclick=newQuiz;$2('#newGoal').onclick=newGoal;$2('#newHabit').onclick=newHabit;$2('#filePicker').onchange=e=>{[...e.target.files].forEach(f=>arr('files').push({id:uid(),name:f.name,size:f.size,type:f.type,added:Date.now()}));saveP();renderFiles()};$2('#fileSearch').oninput=renderFiles;$2('#saveWellbeing').onclick=()=>{const e=document.querySelector('[data-energy].selected')?.dataset.energy;if(!e){toast2('Pick an energy level first.');return}arr('wellbeing').push({id:uid(),energy:Number(e),note:$2('#wellbeingNote').value,date:Date.now()});saveP();$2('#wellbeingNote').value='';document.querySelectorAll('[data-energy]').forEach(x=>x.classList.remove('selected'));renderWellbeing();toast2('Check-in saved')};document.querySelectorAll('[data-energy]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-energy]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.addEventListener('click',e=>{const t=e.target;if(t.dataset.review)reviewDeck(t.dataset.review);if(t.dataset.startquiz)startQuiz(t.dataset.startquiz);if(t.dataset.goal){const g=arr('goals').find(x=>x.id===t.dataset.goal);if(g){g.current=Math.min(g.target,(g.current||0)+1);saveP();renderGoals()}}if(t.dataset.habit){const h=arr('habits').find(x=>x.id===t.dataset.habit);if(h&&h.last!==new Date().toDateString()){h.streak=(h.streak||0)+1;h.last=new Date().toDateString();saveP();renderGoals();toast2('Habit logged')}}if(t.dataset.file){P.files=P.files.filter(x=>x.id!==t.dataset.file);saveP();renderFiles()}if(t.dataset.restore){const x=arr('trash').find(x=>x.id===t.dataset.restore);if(x){const target=x.type==='assignment'?'assignments':x.type==='note'?'notes':null;if(target&&state[target])state[target].push(x.data);P.trash=P.trash.filter(y=>y.id!==x.id);saveP();saveGuest();renderTrash();renderAll()}}});const oldAdd=$2('#add');if(oldAdd)oldAdd.onclick=quickCapture;const sb=$2('#searchBtn');if(sb)sb.onclick=globalSearch;['analytics','files','wellbeing','trash','flashcards','quizzes','goals','assistant'].forEach(id=>{const a=document.querySelector(`a[href="#${id}"]`);if(a)a.addEventListener('click',()=>setTimeout(()=>{if(id==='analytics')renderAnalytics();if(id==='files')renderFiles();if(id==='wellbeing')renderWellbeing();if(id==='trash')renderTrash();if(id==='flashcards')renderDecks();if(id==='quizzes')renderQuizzes();if(id==='goals')renderGoals()},30))});
}
function initPremium(){bootUI();wirePremium();renderDecks();renderQuizzes();renderGoals();renderAnalytics();renderFiles();renderWellbeing();renderTrash();if(location.hash==='#assistant')setTimeout(()=>navRoute(),50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initPremium);else initPremium();
})();